# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobufs/question.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'protobufs/question.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18protobufs/question.proto\x12\x08question\"H\n\x08Question\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tauthor_id\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\x12\x0f\n\x07upvotes\x18\x04 \x01(\x05\"$\n\x0fQuestionFilters\x12\x11\n\tauthor_id\x18\x01 \x01(\t\"&\n\x0fQuestionRequest\x12\x13\n\x0bquestion_id\x18\x01 \x01(\t2\x9e\x02\n\x12QuestionController\x12\x42\n\x16\x43reateOrUpdateQuestion\x12\x12.question.Question\x1a\x12.question.Question\"\x00\x12\x41\n\x0cGetQuestions\x12\x19.question.QuestionFilters\x1a\x12.question.Question\"\x00\x30\x01\x12>\n\x0bGetQuestion\x12\x19.question.QuestionRequest\x1a\x12.question.Question\"\x00\x12\x41\n\x0eUpvoteQuestion\x12\x19.question.QuestionRequest\x1a\x12.question.Question\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobufs.question_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUESTION']._serialized_start=38
  _globals['_QUESTION']._serialized_end=110
  _globals['_QUESTIONFILTERS']._serialized_start=112
  _globals['_QUESTIONFILTERS']._serialized_end=148
  _globals['_QUESTIONREQUEST']._serialized_start=150
  _globals['_QUESTIONREQUEST']._serialized_end=188
  _globals['_QUESTIONCONTROLLER']._serialized_start=191
  _globals['_QUESTIONCONTROLLER']._serialized_end=477
# @@protoc_insertion_point(module_scope)
